# Generated by Django 5.1.1 on 2024-09-26 08:41

import django.db.models.deletion
from django.db import migrations, models


# 下面的这段代码通过执行python manage.py makemigrations polls得来，即通过我们写的models中的类自动创建下面的这些代码
# 这段代码的作用是通过执行python manage.py sqlmigrate polls 0001，
# 自动根据这段代码创建数据库建表（即py代码->数据库建表语句），注意，它并没有真正在数据库中执行迁移，只是把代码输出到屏幕上
# 需要再次运行python manage.py migrate， 在数据库里创建新定义的模型的数据表

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
    ]
